### ISSUE TITLE
nebula-graph run ci test, the storage can't stop,the rebuild index task entered an abnormal loop, causing it not to exit

### ISSUE THREAD

**Issue by laura-ding** [vesoft-inc/nebula-storage#234]
![屏幕快照 2020-12-09 10 17 15](https://user-images.githubusercontent.com/48548375/101565317-c3420d00-3a07-11eb-9b25-4ecae08c5a24.png)

![屏幕快照 2020-12-09 10 18 03](https://user-images.githubusercontent.com/48548375/101565370-dead1800-3a07-11eb-89e7-2c8e25fb323c.png)

**Comment by darionyaphet** [comment]
How to reproduce ?

**Comment by laura-ding** [comment]
> How to reproduce ?

run nebula-graph test

**Comment by darionyaphet** [comment]
> > How to reproduce ?
> 
> run nebula-graph test

Strange

I run it about ten times and didn't show up.
