### ISSUE TITLE
br: the graph service must be restarted after the restoration process

### ISSUE THREAD

**Issue by oldLady344** [vesoft-inc/nebula-storage#254]
After restoration, on nebula-console, I can see the new graph space ("nba") from the backup file. But when I ran `USE nba`, no graph space was found. I restarted the graph service and then all the data can be queried as expected.

![image](https://user-images.githubusercontent.com/61895496/102862894-c22fc780-446c-11eb-9b00-8f8e14f2eb00.png)

**Comment by monadbobo** [comment]
Hello, this problem is caused by the synchronization of schema information and meta, you can wait for a period of time and then the schema synchronization can be used.
