### ISSUE TITLE
按照教程操作，没有对应目录

### ISSUE THREAD

**Issue by wylbjia** [vesoft-inc/nebula-storage#436]
![image](https://user-images.githubusercontent.com/19341559/114664845-defb4e00-9d2e-11eb-8571-cc78fa86f7fc.png)
这里好像没有 util 目录

**Comment by wylbjia** [comment]
@Shylock-Hg 大佬看看

**Comment by Shylock-Hg** [comment]
Had move to https://github.com/vesoft-inc/nebula-br
