### ISSUE TITLE
storage: support scale in to 1 when no space's replica_factor greater than 1

### ISSUE THREAD

**Issue by veezhang** [vesoft-inc/nebula-storage#456]
I failed to scale `storage` back to 1 after scale out it form 1 to 2. And there only have 1 space with `replica_factor=1`.

Logs:
```
I0510 09:18:21.354524   123 Balancer.cpp:306] Too few hosts, no need for balance!
```

**Comment by critical27** [comment]
Bug confirmed, will fix, thx!
