### ISSUE TITLE
VertexCache will destroy the consistency of raft

### ISSUE THREAD

**Issue by cangfengzhs** [vesoft-inc/nebula-storage#530]
1. When reading data from VertexCache, it does not check whether the current part is the leader.
2. When the leader transLeader from part A to part B, and then transLeader to part A, the data in the cache and the data in kvstore may be different
![image](https://user-images.githubusercontent.com/22708345/126481363-78053924-fd28-4d17-b3a4-48cb8c961050.png)

3. When insert/update and read are executed concurrently, vertexCache may hold older data, which is different from that in kvstore.
![image](https://user-images.githubusercontent.com/22708345/126482963-fd6fd6eb-1fbc-4e11-bb73-35842da63433.png)

**Comment by critical27** [comment]
Good job, long history, could replace it with row cache later.
